### ISSUE TITLE
Ajax feature: data and url function is evaluated only once

### ISSUE THREAD

**Issue by vigorouscoding** [nhn/tui.tree#36]
## Version
tui.tree-3.4.0

## Development Environment
Mac/Chrome
Linux/Firefox

## Current Behavior
For every command in the Ajax feature, if `data` and/or `url` are provided as a function, these function(s) are evaluated exactly once and then overwritten with its result.
You can also observe this in your example 8 (https://nhnent.github.io/tui.tree/latest/tutorial-example08-ajax.html) where the data will be evaluated to `{ productId: undefined }` initially and never changes.

```js
tree.enableFeature('Ajax', {
	command: {
		read: {
			url: "/rest",
			dataType: 'json',
			type: 'get',
			data: function(params) {
				return {
					productId: tree.getNodeData(params.nodeId).pid
				};
			}
		}
	}
});	
```

## Expected Behavior
If `data` and/or `url` are provided as a function, the function should be evaluated once for each AJAX request.

If I am using tui.tree incorrectly, please advise how the AJAX feature should be used properly - thanks!

**Comment by Vitaleks-project** [comment]
I have same issue, please help. @vigorouscoding did you resolve your issue?

**Comment by vigorouscoding** [comment]
@Vitaleks-project Sadly no - as this happened in the early stages of the project, we just switched to jstree

**Comment by Vitaleks-project** [comment]
@vigorouscoding ok, ;( thanks for response.
