### ISSUE TITLE
The line is placed on the wrong edge in Draggable UI

### ISSUE THREAD

**Issue by dotaitch** [nhn/tui.tree#56]
## Version

v4.0.0

## Development Environment

Chrome, Safari

## Current Behavior

![tree-draggable-ui](https://user-images.githubusercontent.com/8615506/74123329-ca469600-4c11-11ea-9845-4461a14bb917.gif)

* Chrome: Wrong line for the edge between nodes
* Safari: Wrong line for the edge between nodes and no hover effect

## Expected Behavior

The line should be placed on the edge between nodes that the moving node will be inserted.

**Comment by lja1018** [comment]
This issue was resolved in [v4.0.4](https://github.com/nhn/tui.tree/releases/tag/v4.0.4)
