### ISSUE TITLE
생성된 tree의 전체 data를 얻어 낼 수 있는 방법은 무엇입니까?

### ISSUE THREAD

**Issue by kjkandrea** [nhn/tui.tree#72]
안녕하세요. NHN고도 FE개발팀 김종근 입니다.
사내에서 `tui-tree`를 사용하고 있는데, 궁금한 부분이 있어 문의드립니다. 😊

addNode, removeNode, Editable, Draggable 등 다양한 tui-tree내에서 지원하는 이벤트로 트리의 상태가 변화하는 트리를 만들고 있습니다.
이러한 이벤트를 통해 변화된 트리의 데이터를 트리의 변경내역을 저장할때에, 단 한번 트리의 state를 받아낸 후 이를 저장하고 싶습니다.
대략 다음 코드 처럼요.

``` typescript
// example
const treeId = 'tree'
const treeData = tree.getAllData(treeId) // 이러한 환상적인 메서드는 tui-tree내에는 없는것같습니다 

api.put('/tree/:id', treeData)
```

이와 같이 특정 노드의 state가 아닌, **현재 tree의 state 전체**를 얻어 낼 수 있는 적절한 방법이 있을까요?

[getNodeData(nodeId)](https://nhn.github.io/tui.tree/latest/Tree#getNodeData) 를 통해 특정 트리 노드의 state 데이터를 받아올 수 있단것을 api문서를 통해 학습하였습니다.

제가 지금 생각나는 방법은, 생성된 tree DOM에 접근하여 모든 treeNode의 depth와 아이디를 알아 낸 후,\
getNodeData(nodeId)를 n번 수행하여 변경 된 데이터를 얻어 내는 것입니다.

이보다 더 우수한 방법이 없을까요? 

혹은 `tree.getAllData()`와 같은 메서드를 지원할 향후 계획이 있습니까?

## Summary

아래의 예시와 같이 트리의 모든 데이터를 받아오는 목적을 수행하는 메서드(`getAllData`)의 목적을 달성하는 적절한 방법은 무엇입니까?

``` typescript
// example
const treeId = 'tree'
const treeData = tree.getAllData(treeId)

api.put('/tree/:id', treeData)
```

## Screenshots

none

## Version

latest version

## Additional context

none

**Comment by lja1018** [comment]
안녕하세요! TOAST UI팀 임재언입니다.

불편하시겠지만 사내 문의는 [두레이](https://nhnent.dooray.com/project/2156445857728170161)로 요청해주시면 감사하겠습니다!

감사합니다!
