### ISSUE TITLE
Draggable position error

### ISSUE THREAD

**Issue by KimGenius** [nhn/tui.tree#84]
## Describe the bug
Draggable position error with top area
If top area is empty, working well.
But if there's something in the top area, a position error occurs.

codesandbox: https://codesandbox.io/s/tui-tree-issue-6li9q?file=/index.html
result page: https://6li9q.csb.app/

Please check this error.
Thank you!

## Screenshots
https://user-images.githubusercontent.com/29722636/123352048-7b489900-d599-11eb-9c27-412a561c66dc.mp4

## Desktop (please complete the following information):
 - OS: Window
 - Browser: Chrome
 - Version: 91.0.4472.114

**Comment by jajugoguma** [comment]
@KimGenius 
Thanks for raising the issue!
We will review this issue and take action quickly.
